### PR TITLE
Add @itsrainy as a recognized contributor

### PR DESCRIPTION
**Pull request by fitzgen**
I am nominating or self-nominating a [Recognized Contributor](https://github.com/bytecodealliance/governance/blob/main/TSC/charter.md#recognized-contributors).

**Name:** Rainy Sinclar
**GitHub Username:** @itsrainy
**Projects/SIGs:**

- `wasm-tools`
- Wasmtime

## Nomination

Rainy has been working to improve our differential fuzzing set up in Wasmtime, primarily by extending `wasm-smith` (in the `wasm-tools` repository) with a "no trapping" mode that prevents `wasm-smith` from generating Wasm test cases that will trap. This in turn lets Wasmtime's differential fuzzers execute "deeper" into the test programs so that they are more likely to find divergence between Wasmtime and (for example) V8.

Some pull requests related to this work: https://github.com/bytecodealliance/wasm-tools/pulls?q=author%3Aitsrainy

## Optional: Endorsements

- @fitzgen

- [X] I have read and understood the qualifications for a [Recognized Contributor](https://github.com/technosophos/governance/blob/main/TSC/charter.md#recognized-contributors)

### CODE REVIEW

**Comment by pchickey** [comment]
I endorse Rainy as a recognized contributor.

**Review by alexcrichton — APPROVED** [review]

**Review by peterhuene — APPROVED** [review]

**Comment by tschneidereit** [comment]
I also endorse Rainy: their contributions have been excellent and are clearly worth recognizing.

Note, however, that right now it's a bit unclear how nominations can be accepted, given that we don't currently have a TSC to process them. I brought this up with our Executive Director, @disquisitioner, to discuss with the board.

**Comment by tschneidereit** [comment]
We discussed this nomination at the last TSC meeting, and agree that Rainy's contributions clearly warrant Recognized Contributor status.

@itsrainy, to finalize the addition, please send an email to tsc[[@]bytecodealliance.org to let us know which address to use for communicating with you as a Recognized Contributor, and to confirm that you accept the nomination.

That address will be added to our RCs mailing list, which receives community and project updates every few weeks or so.

Once we've received that email, we'll add you to the mailing list and merge this PR.

**Comment by tschneidereit** [comment]
Thank you for providing your email address—we've added you to the contributors mailing list. More importantly, thank you for contributing to Bytecode Alliance projects! ❤️

**Pull request merged**
