### PR TITLE
Add Jamey Sharp to recognized contributors

### PR DESCRIPTION
**Pull request by fitzgen**
I am nominating or self-nominating a [Recognized Contributor](https://github.com/bytecodealliance/governance/blob/main/TSC/charter.md#recognized-contributors).

**Name:** Jamey Sharp
**GitHub Username:** @jameysharp
**Projects/SIGs:**

- Wasmtime
- Cranelift

## Nomination
Extensive work on Cranelift and Wasmtime in the last few months: https://github.com/bytecodealliance/wasmtime/commits?author=jameysharp

## Optional: Endorsements

- @fitzgen

- [X] I have read and understood the qualifications for a [Recognized Contributor](https://github.com/technosophos/governance/blob/main/TSC/charter.md#recognized-contributors)

### CODE REVIEW

**Comment by jameysharp** [comment]
Here's my sign-off that I'd like to be a Recognized Contributor. Thanks!

**Review by peterhuene — APPROVED** [review]

**Review by cfallin — APPROVED** [review]

**Review by pchickey — APPROVED** [review]

**Comment by tschneidereit** [comment]
I support Jamey's nomination: his work on Wasmtime and Cranelift, particularly around ISLE code generation, is highly valuable and supportive of key goals of the BA.

Note, however, that right now it's a bit unclear how nominations can be accepted, given that we don't currently have a TSC to process them. I brought this up with our Executive Director, @disquisitioner, to discuss with the board.

**Comment by tschneidereit** [comment]
We discussed this nomination at the last TSC meeting, and agree that Jamey's contributions clearly warrant Recognized Contributor status.

@jameysharp, to finalize the addition, please send an email to tsc[[@]bytecodealliance.org to let us know which address to use for communicating with you as a Recognized Contributor, and to confirm that you accept the nomination.

That address will be added to our RCs mailing list, which receives community and project updates every few weeks or so.

Once we've received that email, we'll add you to the mailing list and merge this PR.

**Comment by tschneidereit** [comment]
Thank you for providing your email address—we've added you to the contributors mailing list. More importantly, thank you for contributing to Bytecode Alliance projects! ❤️

**Pull request merged**
