### PR TITLE
Renaming SIG-dynamic-languages to SIG-Guest-Languages

### PR DESCRIPTION
**Pull request by calvinrp**
This PR broadens the scope of the SIG to all guest languages to be more explicitly inclusive.

### CODE REVIEW

**Comment by Kylebrown9** [comment]
After that call, I went looking for definitions of "managed languages" and things that show its common usage in order to determine what language we would use in the charter to draw this line.

One of the first results for managed Languages is [Wikipedia](https://en.wikipedia.org/wiki/Managed_code), which provides the following definition.
> Managed code is computer program code that requires and will execute only under the management of a [Common Language Infrastructure](https://en.wikipedia.org/wiki/Common_Language_Infrastructure) (CLI); [Virtual Execution System](https://en.wikipedia.org/wiki/Virtual_Execution_System) (VES); [virtual machine](https://en.wikipedia.org/wiki/Virtual_machine), e.g. [.NET](https://en.wikipedia.org/wiki/.NET), [CoreFX](https://en.wikipedia.org/wiki/CoreFX), or [.NET Framework](https://en.wikipedia.org/wiki/.NET_Framework); [Common Language Runtime](https://en.wikipedia.org/wiki/Common_Language_Runtime) (CLR); or [Mono](https://en.wikipedia.org/wiki/Mono_(software)). The term was coined by [Microsoft](https://en.wikipedia.org/wiki/Microsoft).

Some other definitions, including one [used on Microsoft's website](https://learn.microsoft.com/en-us/dotnet/standard/managed-code), are broader and are just synonyms for "language with a runtime".
> managed code is just that: code whose execution is managed by a runtime.

There are other places where the term is used broadly (e.g. [Managed Programming Languages and Runtimes 2022](https://soft.vub.ac.be/mplr22/call/)) and narrowly (e.g. [common StackOverflow replies](https://stackoverflow.com/a/3564014/6009385)), but I'm concerned that since there is this mix of understandings of the word declaring that the BA has a "Managed Language" group might imply to some that we are Microsoft-focused.

Beyond the question of "Managed Language" as a term and whether it means what we intend to the majority of our audience, I'm also not sure that the exercise of "line finding" to decide what is and isn't in the group is useful. A decent amount of what is common among languages with runtimes is also in common with languages that don't have them and so discussions and work around componentizing tools and efforts like the dynamic linking project are clearly relevant to runtime/managed languages but also a variety of other languages.

**Review by tschneidereit — CHANGES_REQUESTED** [review]
We discussed this in the TSC meeting yesterday, and agreed that the renaming and scope expansion make sense. We'd like to ask the group chairs for a couple of things though:
1. to evaluate whether the change in scope should be accompanied by any changes in operations
2. to survey all guest language bindings projects and actively reach out to their maintainers to invite them to participate in this SIG

If that all works, then we should merge this PR once the inline comment above is addressed

**Comment by Kylebrown9** [comment]
Thanks TSC, we've reviewed our operations and believe that the subgroup process provides the tools to scale as needed in the short term as we onboard more projects. We'll continue to keep an eye on how our expanded scope affects the way the group needs to be organized. @**Guy Bedford** and I will be reaching out to guest bindings projects authors and publicly announcing the group's new scope once the repos are all renamed and everything is set up and ready to welcome them. 

PR's for the meetings repo ([#106](https://github.com/bytecodealliance/meetings/pull/106)) and the SIG's repo ([#2](https://github.com/bytecodealliance/SIG-Dynamic-Languages/pull/2)) have been opened and will be merged in after this PR is.

**Review by tschneidereit — APPROVED** [review]
Thank you, this all looks great! We just discussed it in the TSC meeting and think this is ready to go

**Pull request merged**
